swagger: "2.0"
info:
  description: "Beacon server Api swagger"
  version: "1.0.0"
  title: "Beacon server"
host: "beacon_server.com:59003"
basePath: "/v1"

paths:
  /user_api_v1/register:
    post:
      tags:
      - "auth"
      summary: "Create user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        description: "create a user"
        required: true
        in: "body"
        schema:
          $ref: "#/definitions/AuthReq"
      responses:
       201:
        description: "create user successful"
        schema:
          $ref: "#/definitions/AuthRep"
       400:
        description: "create user failed"
        schema:
          $ref: "#/definitions/FailReq"
  /user_api_v1/login:
    post:
      tags:
        - "auth"
      summary: "Login and Return token"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          description: "login and return token"
          required: true
          in: "body"
          schema:
            $ref: "#/definitions/LoginReq"
      responses:
        400:
          description: "login failed"
          schema:
            $ref: "#/definitions/FailReq"

        200:
          description: "login successful"
          schema:
            $ref: "#/definitions/LoginRep"


definitions:
  FailReq:
    type: object
    properties:
      data:
        type: "string"
      response:
        type: "string"
      msg:
        type: "string"
  AuthReq:
    type: "object"
    properties:
      user_name:
        type: "string"
      password:
        type: "string"
      password_2:
        type: "string"
      email:
        type: "string"
      mobile:
        type: "string"

  AuthRep:
    type: "object"
    properties:
      data:
        type: "object"
        properties:
          uid:
            type: "string"
      response:
        type: "string"
      msg:
        type: "string"
  LoginReq:
    type: "object"
    properties:
      user_name:
        type: "string"
      password:
        type: "string"
  LoginRep:
    type: "object"
    properties:
      data:
        type: "object"
        properties:
          token:
            type: "string"
          refresh_token:
            type: "string"
      response:
        type: "string"
      msg:
        type: "string"