version: '3'

services:
  redis-sentinel-1:
    image: redis:4.0.12
    container_name: redis-sentinel-1
    restart: always
    networks:
      - redis_network
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    environment:
      TZ: "Asia/Shanghai"
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
  redis-sentinel-2:
    image: redis:4.0.12
    container_name: redis-sentinel-2
    restart: always
    networks:
      - redis_network
    ports:
      - "26380:26380"
    volumes:
      - ./redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    environment:
      TZ: "Asia/Shanghai"
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
  redis-sentinel-3:
    image: redis:4.0.12
    container_name: redis-sentinel-3
    restart: always
    networks:
      - redis_network
    ports:
      - "26381:26381"
    volumes:
      - ./redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    environment:
      TZ: "Asia/Shanghai"
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]

networks:
  redis_network:
    external: true