version: '3'

services:
  redis-server-master:
    image: redis:4.0.12
    container_name: redis-server-master
    restart: always
    network_mode: host
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  redis-server-slave-1:
    image: redis:4.0.12
    container_name: redis-server-slave-1
    restart: always
    network_mode: host
    depends_on:
      - redis-server-master
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
  redis-server-slave-2:
    image: redis:4.0.12
    container_name: redis-server-slave-2
    restart: always
    network_mode: host
    depends_on:
      - redis-server-master
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
